# ****** mongodb settings *****
db:
    auth: false
    port: 27017
    server: 192.168.32.35
    user: mongodb
    user.location: admin
    user.pwd: mongodb


# ****** elastic settings *****
elastic:
    ip: 192.168.33.122
    mongo:
        collection: weibo
        collection.index.field: text
        db: crawDB
        index:
            freq: 200
    port: 9300


# ***** weibo crawler settings ******
weibo:
    cookie: ALF=1495596350; SCF=AmwYx4uq_aQgDJXeS85_nK7Klt9n0WwoP9AGm-gDMcK0Id0XrsC2OSu-s8CkSDYgZKrfbWNhcFTzCcKEm3ePEnA.; SUB=_2A251-QeRDeThGeNI7FQT8SzEzDiIHXVXBanZrDV6PUJbktBeLULHkW0XuImbe9BrUwNNIhWFE3hSfnX6EQ..; SUBP=0033WrSXqPxfM725Ws9jqgMF55529P9D9W5gKlzd-Mei_gQ0z5F4DDK55JpX5o2p5NHD95QfSoMceo2E1hMXWs4Dqcj_i--ci-8hi-2Ei--Xi-z4iK.7i--Xi-iWi-iWi--ci-zRi-zRi--ciKnRiKys; SUHB=0BL4LaI5-U27n_; SSOLoginState=1493006273; _T_WM=4fb5cf5cccb9f35a8573e9743f8fb5cb; M_WEIBOCN_PARAMS=luicode%3D10000012%26lfid%3D1005055676212874_-_FOLLOWERS%26fid%3D1005055676212874_-_FOLLOWERS%26uicode%3D10000012
    crawler:
        threads: 5
    freq: 2
